default:
	tilde news.json
	python3 create_feed.py news.json /home/olivier/projects/boris-behav-obs.github.io/static/atom.xml 5
	cd /home/olivier/projects/boris-behav-obs.github.io; git commit -a -m "added news"; git push origin master

